Fix the Mac Patches
Signed-off-by: Michael Wild <themiwi@users.sourceforge.net>

diff --git a/etc/bashrc b/etc/bashrc
--- a/etc/bashrc
+++ b/etc/bashrc
@@ -223,44 +223,59 @@ SunOS)
     ;;
 
 Darwin)
+    case `sw_vers -productVersion` in
+    10.[0-4])
+        echo "Error: Mac OS X < 10.5 does not work." >&2 || exit 1
+        ;;
+    esac
     export WM_ARCH_BASE=darwin
-    case `uname -p` in
+    WM_SYSROOT="--sysroot `/usr/bin/xcode-select -print-path`/SDKs/MacOSX10.5.sdk"
+    WM_MACOSX_MIN="-mmacosx-version-min=10.5"
+    export WM_CPP='/usr/bin/cpp'
+    if [ -x /usr/bin/llvm-gcc ]; then
+        export WM_CC='/usr/bin/llvm-gcc'
+        export WM_CXX='/usr/bin/llvm-g++'
+    else
+        export WM_CC='/usr/bin/gcc'
+        export WM_CXX='/usr/bin/g++'
+    fi
+    : ${WM_OSX_ARCH:=`uname -p`}
+    case $WM_OSX_ARCH in
     powerpc)
-	export WM_ARCH=darwinPpc
-	;;
+        export WM_ARCH=darwinPpc
+        export WM_CFLAGS="-arch ppc -fPIC $WM_SYSROOT $WM_MACOSX_MIN"
+        export WM_CXXFLAGS="-arch ppc -fPIC $WM_SYSROOT $WM_MACOSX_MIN"
+        export WM_LDFLAGS="-arch ppc $WM_SYSROOT $WM_MACOSX_MIN"
+        ;;
     i386)
-	export WM_ARCH=darwinIntel
+        export WM_ARCH=darwinIntel
         case $WM_ARCH_OPTION in
         32)
             export WM_COMPILER_ARCH='-64'
-            export WM_CC='gcc-mp-4.5'
-            export WM_CXX='g++-mp-4.5'
-            export WM_CFLAGS='-m32 -fPIC'
-            export WM_CXXFLAGS='-m32 -fPIC'
-            export WM_LDFLAGS='-m32'
+            export WM_CFLAGS="-arch i386 -fPIC $WM_SYSROOT $WM_MACOSX_MIN"
+            export WM_CXXFLAGS="-arch i386 -fPIC $WM_SYSROOT $WM_MACOSX_MIN"
+            export WM_LDFLAGS="-arch i386 $WM_SYSROOT $WM_MACOSX_MIN"
             ;;
         64)
             WM_ARCH=darwinIntel64
             export WM_COMPILER_LIB_ARCH=64
-            export WM_CC='gcc-mp-4.5'
-            export WM_CXX='g++-mp-4.5'
-            export WM_CFLAGS='-m64 -fPIC'
-            export WM_CXXFLAGS='-m64 -fPIC'
-            export WM_LDFLAGS='-m64'
+            export WM_CFLAGS="-arch x86_64 -fPIC $WM_SYSROOT $WM_MACOSX_MIN"
+            export WM_CXXFLAGS="-arch x86_64 -fPIC $WM_SYSROOT $WM_MACOSX_MIN"
+            export WM_LDFLAGS="-arch x86_64 $WM_SYSROOT $WM_MACOSX_MIN"
             ;;
         *)
             echo Unknown WM_ARCH_OPTION $WM_ARCH_OPTION, should be 32 or 64
             ;;
         esac
-	;;
+        ;;
     *)
         echo "Unknown architecture "`uname -p` "for Darwin"
     esac
+    unset WM_SYSROOT WM_MACOSX_MIN
 
     export WM_COMPILER=
-    export WM_MPLIB=OPENMPI
-
-    MACOSX_DEPLOYMENT_TARGET=`sw_vers -productVersion`
+    export OMPI_CC=$WM_CC
+    export OMPI_CXX=$WM_CXX
     ;;
 
 *)    # an unsupported operating system
